install:
	yes | cp -rf vm_pageout.c /usr/src/sys/vm/vm_pageout.c
	yes | cp -rf vm_page.c /usr/src/sys/vm/vm_page.c
	yes | cp -rf vm_page.h /usr/src/sys/vm/vm_page.h
	yes | cp -rf vm_phys.c /usr/src/sys/vm/vm_phys.c

uninstall:
	yes | cp -rf unedited/vm_pageout.c /usr/src/sys/vm/vm_pageout.c
	yes | cp -rf unedited/vm_page.c /usr/src/sys/vm/vm_page.c
	yes | cp -rf unedited/vm_page.h /usr/src/sys/vm/vm_page.h
	yes | cp -rf unedited/vm_phys.c /usr/src/sys/vm/vm_phys.c